CREATE TABLE `loans_2020Q1` (
  `id` varchar(255) NOT NULL,
  `member_id` text,
  `loan_amnt` double DEFAULT NULL,
  `funded_amnt` double DEFAULT NULL,
  `funded_amnt_inv` double DEFAULT NULL,
  `term` text,
  `int_rate` double DEFAULT NULL,
  `installment` double DEFAULT NULL,
  `grade` text,
  `sub_grade` text,
  `emp_title` text,
  `emp_length` text,
  `home_ownership` text,
  `annual_inc` double DEFAULT NULL,
  `verification_status` text,
  `issue_d` text,
  `loan_status` text,
  `pymnt_plan` text,
  `url` text,
  `desc` text,
  `purpose` text,
  `title` text,
  `zip_code` text,
  `addr_state` text,
  `dti` double DEFAULT NULL,
  `delinq_2yrs` double DEFAULT NULL,
  `earliest_cr_line` text,
  `fico_range_low` double DEFAULT NULL,
  `fico_range_high` double DEFAULT NULL,
  `inq_last_6mths` double DEFAULT NULL,
  `mths_since_last_delinq` double DEFAULT NULL,
  `mths_since_last_record` double DEFAULT NULL,
  `open_acc` double DEFAULT NULL,
  `pub_rec` double DEFAULT NULL,
  `revol_bal` double DEFAULT NULL,
  `revol_util` double DEFAULT NULL,
  `total_acc` double DEFAULT NULL,
  `initial_list_status` text,
  `out_prncp` double DEFAULT NULL,
  `out_prncp_inv` double DEFAULT NULL,
  `total_pymnt` double DEFAULT NULL,
  `total_pymnt_inv` double DEFAULT NULL,
  `total_rec_prncp` double DEFAULT NULL,
  `total_rec_int` double DEFAULT NULL,
  `total_rec_late_fee` double DEFAULT NULL,
  `recoveries` double DEFAULT NULL,
  `collection_recovery_fee` double DEFAULT NULL,
  `last_pymnt_d` text,
  `last_pymnt_amnt` double DEFAULT NULL,
  `next_pymnt_d` text,
  `last_credit_pull_d` text,
  `last_fico_range_high` double DEFAULT NULL,
  `last_fico_range_low` double DEFAULT NULL,
  `collections_12_mths_ex_med` double DEFAULT NULL,
  `mths_since_last_major_derog` double DEFAULT NULL,
  `policy_code` double DEFAULT NULL,
  `application_type` text,
  `annual_inc_joint` double DEFAULT NULL,
  `dti_joint` double DEFAULT NULL,
  `verification_status_joint` text,
  `acc_now_delinq` double DEFAULT NULL,
  `tot_coll_amt` double DEFAULT NULL,
  `tot_cur_bal` double DEFAULT NULL,
  `open_acc_6m` double DEFAULT NULL,
  `open_act_il` double DEFAULT NULL,
  `open_il_12m` double DEFAULT NULL,
  `open_il_24m` double DEFAULT NULL,
  `mths_since_rcnt_il` double DEFAULT NULL,
  `total_bal_il` double DEFAULT NULL,
  `il_util` double DEFAULT NULL,
  `open_rv_12m` double DEFAULT NULL,
  `open_rv_24m` double DEFAULT NULL,
  `max_bal_bc` double DEFAULT NULL,
  `all_util` double DEFAULT NULL,
  `total_rev_hi_lim` double DEFAULT NULL,
  `inq_fi` double DEFAULT NULL,
  `total_cu_tl` double DEFAULT NULL,
  `inq_last_12m` double DEFAULT NULL,
  `acc_open_past_24mths` double DEFAULT NULL,
  `avg_cur_bal` double DEFAULT NULL,
  `bc_open_to_buy` double DEFAULT NULL,
  `bc_util` double DEFAULT NULL,
  `chargeoff_within_12_mths` double DEFAULT NULL,
  `delinq_amnt` double DEFAULT NULL,
  `mo_sin_old_il_acct` double DEFAULT NULL,
  `mo_sin_old_rev_tl_op` double DEFAULT NULL,
  `mo_sin_rcnt_rev_tl_op` double DEFAULT NULL,
  `mo_sin_rcnt_tl` double DEFAULT NULL,
  `mort_acc` double DEFAULT NULL,
  `mths_since_recent_bc` double DEFAULT NULL,
  `mths_since_recent_bc_dlq` double DEFAULT NULL,
  `mths_since_recent_inq` double DEFAULT NULL,
  `mths_since_recent_revol_delinq` double DEFAULT NULL,
  `num_accts_ever_120_pd` double DEFAULT NULL,
  `num_actv_bc_tl` double DEFAULT NULL,
  `num_actv_rev_tl` double DEFAULT NULL,
  `num_bc_sats` double DEFAULT NULL,
  `num_bc_tl` double DEFAULT NULL,
  `num_il_tl` double DEFAULT NULL,
  `num_op_rev_tl` double DEFAULT NULL,
  `num_rev_accts` double DEFAULT NULL,
  `num_rev_tl_bal_gt_0` double DEFAULT NULL,
  `num_sats` double DEFAULT NULL,
  `num_tl_120dpd_2m` double DEFAULT NULL,
  `num_tl_30dpd` double DEFAULT NULL,
  `num_tl_90g_dpd_24m` double DEFAULT NULL,
  `num_tl_op_past_12m` double DEFAULT NULL,
  `pct_tl_nvr_dlq` double DEFAULT NULL,
  `percent_bc_gt_75` double DEFAULT NULL,
  `pub_rec_bankruptcies` double DEFAULT NULL,
  `tax_liens` double DEFAULT NULL,
  `tot_hi_cred_lim` double DEFAULT NULL,
  `total_bal_ex_mort` double DEFAULT NULL,
  `total_bc_limit` double DEFAULT NULL,
  `total_il_high_credit_limit` double DEFAULT NULL,
  `revol_bal_joint` double DEFAULT NULL,
  `sec_app_fico_range_low` double DEFAULT NULL,
  `sec_app_fico_range_high` double DEFAULT NULL,
  `sec_app_earliest_cr_line` text,
  `sec_app_inq_last_6mths` double DEFAULT NULL,
  `sec_app_mort_acc` double DEFAULT NULL,
  `sec_app_open_acc` double DEFAULT NULL,
  `sec_app_revol_util` double DEFAULT NULL,
  `sec_app_open_act_il` double DEFAULT NULL,
  `sec_app_num_rev_accts` double DEFAULT NULL,
  `sec_app_chargeoff_within_12_mths` double DEFAULT NULL,
  `sec_app_collections_12_mths_ex_med` double DEFAULT NULL,
  `sec_app_mths_since_last_major_derog` double DEFAULT NULL,
  `hardship_flag` text,
  `hardship_type` text,
  `hardship_reason` text,
  `hardship_status` text,
  `deferral_term` double DEFAULT NULL,
  `hardship_amount` double DEFAULT NULL,
  `hardship_start_date` text,
  `hardship_end_date` text,
  `payment_plan_start_date` text,
  `hardship_length` double DEFAULT NULL,
  `hardship_dpd` double DEFAULT NULL,
  `hardship_loan_status` text,
  `orig_projected_additional_accrued_interest` double DEFAULT NULL,
  `hardship_payoff_balance_amount` double DEFAULT NULL,
  `hardship_last_payment_amount` double DEFAULT NULL,
  `debt_settlement_flag` text,
  `debt_settlement_flag_date` text,
  `settlement_status` text,
  `settlement_date` text,
  `settlement_amount` double DEFAULT NULL,
  `settlement_percentage` double DEFAULT NULL,
  `settlement_term` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci