#Create Table
DROP TABLE IF EXISTS `pmthist_all`;
CREATE TABLE `pmthist_all` (
`LOAN_ID` varchar(255) NOT NULL,
`PBAL_BEG_PERIOD` double DEFAULT NULL,
`PRNCP_PAID` double DEFAULT NULL,
`INT_PAID` double DEFAULT NULL,
`FEE_PAID` double DEFAULT NULL,
`DUE_AMT` double DEFAULT NULL,
`RECEIVED_AMT` double DEFAULT NULL,
`PERIOD_END_LSTAT` text DEFAULT NULL,
`MONTH` text DEFAULT NULL,
`PBAL_END_PERIOD` double DEFAULT NULL,
`MOB` double DEFAULT NULL,
`COAMT` double DEFAULT NULL,
`VINTAGE` text DEFAULT NULL,
`PCO_RECOVERY` double DEFAULT NULL,
`PCO_COLLECTION_FEE` double DEFAULT NULL,
`PRE_PAY` double DEFAULT NULL,
`CHARGE_OFF` double DEFAULT NULL,
`LC_FEE` double DEFAULT NULL,
`NET_RECOVERY` double DEFAULT NULL,
`RESIDUAL_RECEIVED` double DEFAULT NULL,
`NET_GL` double DEFAULT NULL,
`NET_GL_CUM` double DEFAULT NULL,
`BV` double DEFAULT NULL,
`EV` double DEFAULT NULL,
`NET_RETURN` double DEFAULT NULL,
id BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
;

#Load data from CSV file
LOAD DATA INFILE 'E:/DATABASES/LENDING_CLUB/PAYMENT_HIST_DATA/PREPROCESSED/PMTHIST_ALL_202004.csv' 
REPLACE INTO TABLE lendingclub.pmthist_all
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(
	LOAN_ID,
	@PBAL_BEG_PERIOD,
	@PRNCP_PAID,
	@INT_PAID,
	@FEE_PAID,
	@DUE_AMT,
	@RECEIVED_AMT,
	@PERIOD_END_LSTAT,
	@`MONTH`,
	@PBAL_END_PERIOD,
	@MOB,
	@COAMT,
	@VINTAGE,
	@PCO_RECOVERY,
	@PCO_COLLECTION_FEE,
    @PRE_PAY,
	@CHARGE_OFF,
    @LC_FEE,
    @NET_RECOVERY,
    @RESIDUAL_RECEIVED,
    @NET_GL,
    @NET_GL_CUM,
    @BV,
    @EV,
    @NET_RETURN
    )
    
#If functions for if blank insert NULL
    SET PBAL_BEG_PERIOD = IF(@PBAL_BEG_PERIOD = '', 0, @PBAL_BEG_PERIOD),
    PRNCP_PAID = IF(@PRNCP_PAID = '', 0, @PRNCP_PAID),
    INT_PAID = IF(@INT_PAID = '', 0, @INT_PAID),
    FEE_PAID = IF(@FEE_PAID = '', 0, @FEE_PAID),
    DUE_AMT = IF(@DUE_AMT = '', 0, @DUE_AMT),
    RECEIVED_AMT = IF(@RECEIVED_AMT = '', 0, @RECEIVED_AMT),
    PERIOD_END_LSTAT = IF(@PERIOD_END_LSTAT = '', 0, @PERIOD_END_LSTAT),
    `MONTH` = IF(@`MONTH` = '', NULL, @`MONTH`),
    PBAL_END_PERIOD = IF(@PBAL_END_PERIOD = '', 0, @PBAL_END_PERIOD),
    MOB = IF(@MOB = '', NULL, @MOB),
    COAMT = IF(@COAMT = '', 0, @COAMT),
    VINTAGE = IF(@VINTAGE = '', NULL, @VINTAGE),
    PCO_RECOVERY = IF(@PCO_RECOVERY = '', 0, @PCO_RECOVERY),
    PCO_COLLECTION_FEE = IF(@PCO_COLLECTION_FEE = '', 0, @PCO_COLLECTION_FEE),
    PRE_PAY = IF(@PRE_PAY = '', 0, @PRE_PAY),
	CHARGE_OFF = IF(@CHARGE_OFF = '', 0, @CHARGE_OFF),
    LC_FEE = IF(@LC_FEE = '', 0, @LC_FEE),
    NET_RECOVERY = IF(@NET_RECOVERY = '', 0, @NET_RECOVERY),
    RESIDUAL_RECEIVED = IF(@RESIDUAL_RECEIVED = '', 0, @RESIDUAL_RECEIVED),
    NET_GL = IF(@NET_GL = '', 0, @NET_GL),
    NET_GL_CUM = IF(@NET_GL_CUM = '', 0, @NET_GL_CUM),
	BV = IF(@BV = '', 0, @BV),
	EV = IF(@EV = '', 0, @EV),
	NET_RETURN = IF(@NET_RETURN = '', 0, @NET_RETURN)
;




